### ISSUE TITLE
Triton and xformer errors?

### ISSUE THREAD

**Issue by Elsword016** [facebookresearch/dinov2#3]
I am getting this error:
Operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 64
    
   I tried to build xformers from source and then tried to install triton as well, its not working, does anyone faced this issue. I'm on Windows btw

**Comment by SikanderBinMukaram** [comment]
I am getting similar error:
`NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 257, 6, 64) (torch.float32)
     key         : shape=(1, 257, 6, 64) (torch.float32)
     value       : shape=(1, 257, 6, 64) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`flshattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 64`

**Comment by shubhamkaushal765** [comment]
I was getting a similar error, when I was loading from hub
```dinov2_vitb14 = torch.hub.load('facebookresearch/dinov2', 'dinov2_vitb14')```

changing it to below works (use cuda):
```dinov2_vitb14 = torch.hub.load('facebookresearch/dinov2', 'dinov2_vitb14').cuda()```

**Comment by alihassanijr** [comment]
If you're on CPU, you should uninstall xFormers, because if python finds xFormers, it will try and use their memory efficient attention, which is pretty much CUDA-only (like FMHA and FlashAttention). That's why you're getting the cutlass error @SikanderBinMukaram , and that's why if you switch to CUDA like @shubhamkaushal765 it'll work.

I think @Elsword016 's issue is different though, my guess is either triton or xFormers weren't compiled correctly since you're on Windows. Can you try and install those separately following their instructions (because I'm pretty sure both support Windows.)

https://github.com/facebookresearch/xformers/

https://github.com/openai/triton

**Comment by patricklabatut** [comment]
Thanks @alihassanijr for helping out!

To be clear loading a model (via `torch.hub.load()`) should not actually require xFormers (but can optionally use it if available). If you have xFormers already installed, do make sure it is at least `0.0.18` (it's the only version thoroughly tested), otherwise please upgrade and / or reinstall from source.

**Comment by alihassanijr** [comment]
@patricklabatut Not a problem, happy to help. I did start a PR that adds just a few lines to check if it's running on CUDA and only then attempt to use memory efficient attention. Not sure if it'll be necessary, but I figured I'd start the PR so it's there as an option.

**Comment by abtExp** [comment]
Still getting the same error trying with both 0.0.18 and the pre version
![stable](https://user-images.githubusercontent.com/15520739/233607123-92dd5ccc-79f8-49eb-8e46-70702c1b2922.png)
Stable config




![pre](https://user-images.githubusercontent.com/15520739/233607234-40ef6aed-8de6-496d-ab66-008e7ee00b57.png)
Pre Config



Error 

![image](https://user-images.githubusercontent.com/15520739/233607334-7d7073d3-7711-434f-8ba8-a195202cdbb7.png)

**Comment by abtExp** [comment]
running on docker with CUDA 11.8 and ubuntu 22.04

**Comment by abtExp** [comment]
@alihassanijr thanks, that was the issue🤦

**Comment by patricklabatut** [comment]
With #180 it's now possible to force not trying to use `xFormers` (even when it is installed and can be imported) by setting the `XFORMERS_DISABLED` environment variable. That's obviously a workaround and hopefully a more elegant solution could eventually be provided by the `xFormers` library instead. The README / Installation instructions will be updated accordingly. Closing.
