### ISSUE TITLE
How is the data loading handled after a restart ?

### ISSUE THREAD

**Issue by CharlieCheckpt** [facebookresearch/dinov2#341]
Hi,

Thank you for providing this nice repo :)

When the training is interrupted and restarted, my understanding is that specifying `--output_dir = path/to/my/previous/run` will make the training load the latest checkpoint from the previous run. Cf: 
https://github.com/facebookresearch/dinov2/blob/2302b6bf46953431b969155307b9bed152754069/dinov2/train/train.py#L151

But what about the data loading ? Does the data loading start again from scratch ?  It seems yes, because I don't see any the processed indices of the dataset saved, but I'm not sure. Cf:
https://github.com/facebookresearch/dinov2/blob/2302b6bf46953431b969155307b9bed152754069/dinov2/train/train.py#L194

If the data loading is indeed started again from scratch, this is problematic for my case, as I plan to run only one epoch on a rather large dataset, with multiple restarts. Any advice on how to proceed ?

Thank you

**Comment by qasfb** [comment]
Check this: 
https://github.com/facebookresearch/dinov2/blob/2302b6bf46953431b969155307b9bed152754069/dinov2/train/train.py#L200-L211

If you uncomment what is commented, in theory it should do what you are looking for, but I invite you to double-check what the sampler does with 2 GPUs, because this is not the main codepath and therefore not thoroughly tested.

**Comment by qasfb** [comment]
yes all is supposed to work correctly in the context of preemptions and requeue, except for the data loader resume as mentioned
