### ISSUE TITLE
Do black borders affect model performance?

### ISSUE THREAD

**Issue by seamie6** [facebookresearch/dinov2#444]
Another GitHUb project Metric3D: https://github.com/YvanYin/Metric3D says you should not use images with black borders and such as this affects the models ability to predict depth. 
I am wondering if something similar happens with DINOv2? Or can it effectively handle images with black borders and such?
Thank you.

**Comment by heyoeyo** [comment]
The black borders would definitely be included in the processing of any image through dinov2, though whether or not this has a negative impact depends on how the output is being used.

For depth-prediction specifically, I would think it would always cause problems, since it's not clear what depth should be reported for the borders. So it would be better to remove them before processing (this could be done automatically, for example, by removing rows near the top and bottom whose pixel values sum to 0 or very nearly zero).

For other tasks, like matching similar images for example, keeping the black borders might be important. Especially if the borders imply something about the image (e.g. that it's a cinematic shot).

**Comment by seamie6** [comment]
Thank you. One additional question, the feature vectors for each model are:
    384 for ViT-S.
    768 for ViT-B.
    1024 for ViT-L.
    1536 for ViT-g.
    
Why is the ViT-L model 1024, and not 1152 = 384x3
Any specific reason this is the case apart from 1024 being 2^10

**Comment by heyoeyo** [comment]
That's a good question! I'm not really sure, but I doubt it's anything profound. I know in some cases models are sized in order to match the parameter count of some prior research to help with comparisons (i.e. 'our new model is the same size as this previous model, but performs X% better'), so that may be part of it. Though I quickly glanced through the paper and didn't see anything like this mentioned.

I'd assume is like you mentioned, that 1024 is just a nice/standard number to use, and wouldn't be surprised if that's all there is to it.

**Comment by seamie6** [comment]
Thank you
